name: piano_example
description: Example app for the Piano package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <3.13.5"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  piano:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
