name: piano
description: Utilities and widgets for working with piano sheet music learning.
version: 1.0.0
author: Craig McMahon
homepage: https://www.handform.net
repository: https://github.com/craigomac/piano

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  equatable: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  freezed: ^0.14.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
