name: piano
description: Utilities and widgets for working with piano sheet music learning.
version: 1.0.0
author:
homepage: https://www.handform.net

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed:
  equatable:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
